pub type Key = i32;

pub const KEY_SPACE: Key = 32;
pub const KEY_APOSTROPHE: Key = 39; /* ' */
pub const KEY_COMMA: Key = 44; /* , */
pub const KEY_MINUS: Key = 45; /* - */
pub const KEY_PERIOD: Key = 46; /* . */
pub const KEY_SLASH: Key = 47; /* / */
pub const KEY_0: Key = 48;
pub const KEY_1: Key = 49;
pub const KEY_2: Key = 50;
pub const KEY_3: Key = 51;
pub const KEY_4: Key = 52;
pub const KEY_5: Key = 53;
pub const KEY_6: Key = 54;
pub const KEY_7: Key = 55;
pub const KEY_8: Key = 56;
pub const KEY_9: Key = 57;
pub const KEY_SEMICOLON: Key = 59; /* ; */
pub const KEY_EQUAL: Key = 61; /* = */
pub const KEY_A: Key = 65;
pub const KEY_B: Key = 66;
pub const KEY_C: Key = 67;
pub const KEY_D: Key = 68;
pub const KEY_E: Key = 69;
pub const KEY_F: Key = 70;
pub const KEY_G: Key = 71;
pub const KEY_H: Key = 72;
pub const KEY_I: Key = 73;
pub const KEY_J: Key = 74;
pub const KEY_K: Key = 75;
pub const KEY_L: Key = 76;
pub const KEY_M: Key = 77;
pub const KEY_N: Key = 78;
pub const KEY_O: Key = 79;
pub const KEY_P: Key = 80;
pub const KEY_Q: Key = 81;
pub const KEY_R: Key = 82;
pub const KEY_S: Key = 83;
pub const KEY_T: Key = 84;
pub const KEY_U: Key = 85;
pub const KEY_V: Key = 86;
pub const KEY_W: Key = 87;
pub const KEY_X: Key = 88;
pub const KEY_Y: Key = 89;
pub const KEY_Z: Key = 90;
pub const KEY_LEFT_BRACKET: Key = 91; /* [ */
pub const KEY_BACKSLASH: Key = 92; /* \ */
pub const KEY_RIGHT_BRACKET: Key = 93; /* ] */
pub const KEY_GRAVE_ACCENT: Key = 96; /* ` */
pub const KEY_WORLD_1: Key = 161; /* non-US #1 */
pub const KEY_WORLD_2: Key = 162; /* non-US #2 */
pub const KEY_ESCAPE: Key = 256;
pub const KEY_ENTER: Key = 257;
pub const KEY_TAB: Key = 258;
pub const KEY_BACKSPACE: Key = 259;
pub const KEY_INSERT: Key = 260;
pub const KEY_DELETE: Key = 261;
pub const KEY_RIGHT: Key = 262;
pub const KEY_LEFT: Key = 263;
pub const KEY_DOWN: Key = 264;
pub const KEY_UP: Key = 265;
pub const KEY_PAGE_UP: Key = 266;
pub const KEY_PAGE_DOWN: Key = 267;
pub const KEY_HOME: Key = 268;
pub const KEY_END: Key = 269;
pub const KEY_CAPS_LOCK: Key = 280;
pub const KEY_SCROLL_LOCK: Key = 281;
pub const KEY_NUM_LOCK: Key = 282;
pub const KEY_PRINT_SCREEN: Key = 283;
pub const KEY_PAUSE: Key = 284;
pub const KEY_F1: Key = 290;
pub const KEY_F2: Key = 291;
pub const KEY_F3: Key = 292;
pub const KEY_F4: Key = 293;
pub const KEY_F5: Key = 294;
pub const KEY_F6: Key = 295;
pub const KEY_F7: Key = 296;
pub const KEY_F8: Key = 297;
pub const KEY_F9: Key = 298;
pub const KEY_F10: Key = 299;
pub const KEY_F11: Key = 300;
pub const KEY_F12: Key = 301;
pub const KEY_F13: Key = 302;
pub const KEY_F14: Key = 303;
pub const KEY_F15: Key = 304;
pub const KEY_F16: Key = 305;
pub const KEY_F17: Key = 306;
pub const KEY_F18: Key = 307;
pub const KEY_F19: Key = 308;
pub const KEY_F20: Key = 309;
pub const KEY_F21: Key = 310;
pub const KEY_F22: Key = 311;
pub const KEY_F23: Key = 312;
pub const KEY_F24: Key = 313;
pub const KEY_F25: Key = 314;
pub const KEY_KP_0: Key = 320;
pub const KEY_KP_1: Key = 321;
pub const KEY_KP_2: Key = 322;
pub const KEY_KP_3: Key = 323;
pub const KEY_KP_4: Key = 324;
pub const KEY_KP_5: Key = 325;
pub const KEY_KP_6: Key = 326;
pub const KEY_KP_7: Key = 327;
pub const KEY_KP_8: Key = 328;
pub const KEY_KP_9: Key = 329;
pub const KEY_KP_DECIMAL: Key = 330;
pub const KEY_KP_DIVIDE: Key = 331;
pub const KEY_KP_MULTIPLY: Key = 332;
pub const KEY_KP_SUBTRACT: Key = 333;
pub const KEY_KP_ADD: Key = 334;
pub const KEY_KP_ENTER: Key = 335;
pub const KEY_KP_EQUAL: Key = 336;
pub const KEY_LEFT_SHIFT: Key = 340;
pub const KEY_LEFT_CONTROL: Key = 341;
pub const KEY_LEFT_ALT: Key = 342;
pub const KEY_LEFT_SUPER: Key = 343;
pub const KEY_RIGHT_SHIFT: Key = 344;
pub const KEY_RIGHT_CONTROL: Key = 345;
pub const KEY_RIGHT_ALT: Key = 346;
pub const KEY_RIGHT_SUPER: Key = 347;
pub const KEY_MENU: Key = 348;
